spring:
  datasource: # default
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid: # config all of these by default
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis: # config all of these by default
    host: localhost
    database: 0
    port: 6379
    password: # null
    timeout: 300m

minio:
  endpoint: http://localhost:9000 # default
  bucketName: petmall
  accessKey: minioadmin
  secretKey: minioadmin

logging: # default
  level:
    root: info
    com.pet.mall: debug

logstash: # default
  host: localhost
  enableInnerLog: false