server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: reader
    password: 123456
    druid:
      initial-size: 5 #
      min-idle: 10 #
      max-active: 20 #
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #
      stat-view-servlet: #
        login-username: druid
        login-password: druid

  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port

  redis:
    host: redis # 
    database: 0 # 
    port: 6379 # 
    password: # 
    timeout: 300ms # 

  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.pet.mall: info

logstash:
  host: logstash

